/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashirli
 */
public class Melumatlar extends javax.swing.JFrame {

    /**
     * Creates new form Melumatlar
     */
    public Melumatlar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("TEST MEQSEDLIDIR!\n---------------------------------------------------------------------------------------------------------------------------\nKartlar:\nOnline kart sifarişi xidməti: İndi siz evdən çıxmadan plastik kart sifariş edə bilərsiniz. \nXXX Bankın təqdim etdiyi plastik kartlar ilə üstünlüklərdən yararlanmaq üçün tələsin.\n İstənilən yerdə istifadəsinin rahatlığı və üstünlükləri ilə XXXBank hesab kartları hər kəsin ürəyincə olacaq.\n---------------------------------------------------------------------------------------------------------------------------\nPulsuz 3 illik kartı 500 AZN / 300 USD / 250 EUR ilkin mədaxil etməklə əldə edə bilərsən!\nKartın yalnız şaquli formasına görə deyil, həm də kənarının rənginə görə pul qabında digər kartlardan fərqlənəcək. \nTezliklə bu kartı daha çox sevəcəksən. Debet kart ilə dünyanın istənilən ölkəsində rahat alış-veriş, onlayn ödənişlər edə, restoran, \nbilet və digər xidmətlərdən istifadə edə və ya vəsaiti rahat nağdlaşdıra bilərsiniz. \nHəmçinin debet kart şifrəsini online pin set xidmətindən yararlanaraq təyin edə bilərsiniz. \nBu və daha çox üstünlüklərdən yararlanmaq üçün aşağıdakı sifariş formasından istifadə edərək debet kart sifarişi edə bilərsiniz.\n\n---------------------------------------------------------------------------------------------------------------------------\nKredit şertleri:\n\n\nTələblər\nAR şəxsiyyət vəsiqəsi (Qeyri rezident şəxslər üçün xarici pasport)\nYaş həddi – min. 18 yaş\n \n\nKredit xətti kart ilə alındıqda ATM-lərdən nağdlaşdırma komissiyası:\nXXX Bank ATM və ofislərindən - 1%\n\nXXXcard şəbəkəsinin üzvü olan digər rezident banklardan - 2% (min.2 AZN/USD/EUR)\n\nXXXcard şəbəkəsinin üzvü olmayan digər rezident və qeyri-rezident banklardan - 3% (min.3 AZN/USD/EUR)\n---------------------------------------------------------------------------------------------------------------------------\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Melumatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Melumatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Melumatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Melumatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Melumatlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
