
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashirli
 */
public class Messenger extends javax.swing.JFrame {
    DefaultListModel model_bot=new DefaultListModel();
    DefaultListModel model_ist=new DefaultListModel();
    String musteri;
   
    
    /**
     * Creates new form Messanger
     */
    public Messenger() {
        
        initComponents();
        mesajlasma_bot.setModel(model_bot);
        mesajlasma_ist.setModel(model_ist);
        baslangic_mesaj();
       
        mesaj_gonderen.setVisible(false);
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        profil_sekli = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mesaj_gonderen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mesajlasma_bot = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mesajlasma_ist = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cixis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XXXX Messenger");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 51));
        jTextField1.setText("XXXXXXX Bank");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        profil_sekli.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Temp-60x40.jpg")); // NOI18N
        profil_sekli.setMaximumSize(new java.awt.Dimension(400, 300));
        profil_sekli.setMinimumSize(new java.awt.Dimension(400, 300));
        profil_sekli.setPreferredSize(new java.awt.Dimension(400, 300));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mesaj_gonderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaj_gonderenActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 7)); // NOI18N
        jButton2.setText("Gönder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mesajlasma_bot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(mesajlasma_bot);

        mesajlasma_ist.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(mesajlasma_ist);

        jMenu1.setText("Tenzimlemeler");

        cixis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cixis.setText("Çıxış etmek");
        cixis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cixisActionPerformed(evt);
            }
        });
        jMenu1.add(cixis);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(profil_sekli, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(mesaj_gonderen, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profil_sekli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mesaj_gonderen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         LocalTime lt=LocalTime.now();
        jButton1.setVisible(false);
          mesaj_gonderen.setVisible(true);
        jButton2.setVisible(true);
        baslangic_mesaji_sil();
        model_ist.addElement(lt.format(DateTimeFormatter.ofPattern("HH:mm"))+" "+musteri+":");
        model_ist.addElement("/start");
        
       
        model_bot.addElement(" ");   model_bot.addElement(lt.format(DateTimeFormatter.ofPattern("HH:mm"))+" Bot:"); 
        model_bot.addElement("Banka xoş geldiniz. Bu emeliyyatlar var:");
        model_bot.addElement("1. Bank haqqında");
        model_bot.addElement("2. Diger emeliyyatlar");
        model_bot.addElement("Davam etmek ucun /davam yazin.");
        model_ist.addElement(" ");  model_ist.addElement(" "); model_ist.addElement(" "); model_ist.addElement(" ");
         
         
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         LocalTime lt=LocalTime.now();
        String mesaj=mesaj_gonderen.getText().toString();
        
          model_ist.addElement(lt.format(DateTimeFormatter.ofPattern("HH:mm"))+" "+musteri+":");
        model_ist.addElement(mesaj);
        model_ist.addElement(" ");
        mesaj_gonderen.setText("");
        
        if(mesaj.equals("/davam")){
            model_bot.addElement(" "); model_bot.addElement(" "); 
            // BURDA EDILECEKLER YAZILACAQ!!!
        
           
            Emeliyyatlar e=new Emeliyyatlar();
        
            e.setVisible(true);
            setVisible(false);
            
        }else {
            
            model_bot.addElement(" ");   model_bot.addElement(lt.format(DateTimeFormatter.ofPattern("HH:mm"))+" Bot:"); 
             model_bot.addElement("Bele bir emeliyyat yoxdur.");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mesaj_gonderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaj_gonderenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaj_gonderenActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cixisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cixisActionPerformed
        // TODO add your handling code here:

        JOptionPane.showInputDialog("Fikirlerinizi bizimle bölüşün.");
        JOptionPane.showMessageDialog(this, "Bizi seçdiyiniz üçün teşekkürler!");
        System.exit(0);
    }//GEN-LAST:event_cixisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Messenger().setVisible(true);
            }
        });
    }
    public void baslangic_mesaji_sil(){
        model_bot.clear();
        
    }
public void baslangic_mesaj(){
     LocalTime lt=LocalTime.now();
    for(int i=1;i<10;i++){
    model_bot.addElement(" ");
    }
    model_bot.addElement(lt.format(DateTimeFormatter.ofPattern("HH:mm"))+"  Bot:");
        model_bot.addElement("       Başlamaq üçün start basın");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cixis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mesaj_gonderen;
    private javax.swing.JList<String> mesajlasma_bot;
    private javax.swing.JList<String> mesajlasma_ist;
    private javax.swing.JLabel profil_sekli;
    // End of variables declaration//GEN-END:variables
}
